spring:
  h2:
    console:
      enabled: false

allowed-origins: "*"
default-password: password

---

spring:
  jpa:
    generate-ddl: true
  config:
    activate:
      on-profile: prod

allowed-origins: "*"

logging:
  level:
    org:
      hibernate: error
      springframework.core: error
      springframework.web: error
    root: error
